import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from 'next/link';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="relative min-h-screen">
          <header className="container mx-auto px-4 py-6">
            <div className="flex items-center justify-between">
              <Link 
                href="/" 
                className="text-3xl font-bold text-white hover:text-gray-200 transition-colors"
              >
                Memetica
              </Link>
              <nav className="flex items-center gap-6">
                <Link 
                  href="/minds" 
                  className="text-gray-300 hover:text-white transition-colors"
                >
                  Explore
                </Link>
                <Link 
                  href="/minds/create" 
                  className="px-4 py-2 bg-blue-500 hover:bg-blue-600 
                    text-white rounded-lg transition-colors"
                >
                  Add Mind
                </Link>
              </nav>
            </div>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
